# Generated by Django 3.0.4 on 2020-07-08 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_from', models.CharField(max_length=200)),
                ('location_to', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.CharField(default='', max_length=300)),
                ('capacity', models.CharField(default='', max_length=100)),
                ('volume', models.CharField(default='', max_length=100)),
                ('cost', models.CharField(default='', max_length=100)),
                ('company_name', models.CharField(blank=True, default='', max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('additional_information', models.CharField(blank=True, default='', max_length=300)),
                ('top', models.BooleanField(default='False')),
                ('top_date', models.DateField(blank=True, null=True)),
                ('top_date_end', models.DateField(blank=True, null=True)),
                ('pin', models.BooleanField(default='False')),
                ('pin_date', models.DateField(blank=True, null=True)),
                ('pin_date_end', models.DateField(blank=True, null=True)),
                ('created', models.DateField()),
                ('views', models.IntegerField(default='0')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_from', models.CharField(max_length=200)),
                ('location_to', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('weight', models.CharField(max_length=100)),
                ('volume', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, default='', max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('additional_information', models.CharField(blank=True, default='', max_length=300)),
                ('top', models.BooleanField(default='False')),
                ('top_date', models.DateField(blank=True, null=True)),
                ('top_date_end', models.DateField(blank=True, null=True)),
                ('pin', models.BooleanField(default='False')),
                ('pin_date', models.DateField(blank=True, null=True)),
                ('pin_date_end', models.DateField(blank=True, null=True)),
                ('created', models.DateField()),
                ('views', models.IntegerField(default='0')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
